name: Deploy Cloud Function GCP

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v4'

      - name: 'Authorization GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/462962855097/locations/global/workloadIdentityPools/github/providers/my-repo'
      
