name: Stats

on:
  # Cada vez que se haga un push a la rama main se ejecutará el workflow
  # push: 
  #   branches: [ main ]
  # 
  schedule:
    # Cada vez que sea la medianoche se ejecutará el workflow || minuto hora dia mes dia_semana
    - cron: '0 0 * * *'

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      with:
        name: 'my-function'
        runtime: 'nodejs20'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
